name: Build, Quality, Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  default-core:
    name: "Default"
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}-core

      - name: Install dependencies
        run: npm ci

      - name: Lint
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run lint

      - name: Build
        run: npm run build
